modLoader="javafml"
loaderVersion="[24,)"

[[mods]] #mandatory
	modId="thrivecraft"
	version="1.0"
	displayName="Thrive Craft"
	credits="Herobrain_gamer For Coding, GamerGabriel For Textures, TheTrueDuility For Helping"
	authors="Herobrain_gamer, GamerGabriel, TheTrueDuility"
	description='''Ian Please Add More Information'''

[[dependencies.thrivecraft]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.thrivecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.thrivecraft]]
    modId="pixelcore"
    mandatory=true
    versionRange="[1.0]"
    ordering="NONE"
    side="BOTH"