modLoader="javafml"
loaderVersion="[24,)"

[[mods]] #mandatory
	modId="thrivecraft"
	version="0.1"
	displayName="Thrive Craft"
	credits="Herobrain_gamer For Coding, GamerGabriel For Textures, TheTrueDuility For Ideas AKA The Slave Owner"
	authors="Herobrain_gamer, GamerGabriel, TheTrueDuility"
	description='''Ian Please Add More Information'''

[[dependencies.thrivecraft]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.thrivecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"